# Generated by Django 5.0.6 on 2024-07-06 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_collection_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
    ]
