# Generated by Django 5.0.6 on 2024-07-07 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='category',
        ),
    ]
