# Generated by Django 5.0.6 on 2024-07-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignUp',
            new_name='Register',
        ),
    ]
