# Generated by Django 5.0.6 on 2024-07-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_signup_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
