# Generated by Django 5.0.6 on 2024-07-14 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
