# Generated by Django 5.0.6 on 2024-07-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewArrivals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_arrival', models.CharField(max_length=100)),
                ('new_arrival_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='TopSellingProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_selling_product', models.CharField(max_length=100)),
                ('top_selling_product_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
