# Generated by Django 5.0.6 on 2024-07-15 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_newarrivals_topsellingproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_arrival',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.newarrivals'),
        ),
        migrations.AddField(
            model_name='product',
            name='top_selling_product',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.topsellingproducts'),
        ),
    ]
