# Generated by Django 5.0.6 on 2024-07-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_new_arrival_product_top_selling_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newarrivals',
            name='new_arrival_image',
        ),
        migrations.RemoveField(
            model_name='topsellingproducts',
            name='top_selling_product_image',
        ),
    ]
