# Generated by Django 5.0.6 on 2024-07-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_newarrivals_new_arrival_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_arrival',
        ),
        migrations.RemoveField(
            model_name='product',
            name='top_selling_product',
        ),
        migrations.DeleteModel(
            name='NewArrivals',
        ),
        migrations.DeleteModel(
            name='TopSellingProducts',
        ),
    ]
