# Generated by Django 5.0.6 on 2024-07-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_remove_cart_product_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
