# Generated by Django 5.0.6 on 2024-07-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_wishlist_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_selling_product', models.CharField(max_length=100)),
                ('url', models.URLField(default='https://example.com')),
            ],
        ),
        migrations.CreateModel(
            name='TopSellingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_arrivals', models.CharField(max_length=100)),
                ('url', models.URLField(default='https://example.com')),
            ],
        ),
    ]
