# Generated by Django 5.0.6 on 2024-07-24 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_newarrival_topsellingproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newarrival',
            old_name='top_selling_product',
            new_name='new_arrivals',
        ),
        migrations.RenameField(
            model_name='topsellingproduct',
            old_name='new_arrivals',
            new_name='top_selling_product',
        ),
    ]
