# Generated by Django 5.0.6 on 2024-07-24 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_rename_top_selling_product_newarrival_new_arrivals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_arrivals',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.newarrival'),
        ),
        migrations.AddField(
            model_name='product',
            name='top_selling_product',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.topsellingproduct'),
        ),
    ]
