# Generated by Django 5.0.6 on 2024-07-24 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_product_new_arrivals_product_top_selling_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_arrivals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.newarrival'),
        ),
        migrations.AlterField(
            model_name='product',
            name='top_selling_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.topsellingproduct'),
        ),
    ]
