# Generated by Django 5.0.6 on 2024-07-26 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_remove_order_created_order_date_order_phone_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='zipcode',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 22, 54, 35, 723258)),
        ),
    ]
