# Generated by Django 5.0.6 on 2024-07-30 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_banner_alter_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='description',
            new_name='banner_description',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='image',
            new_name='banner_image',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='title',
            new_name='banner_title',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 30, 23, 17, 50, 651743)),
        ),
    ]
