# Generated by Django 5.0.6 on 2024-07-30 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_rename_description_banner_banner_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 31, 0, 0, 41, 3125)),
        ),
    ]
