# Generated by Django 5.0.6 on 2024-07-31 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_order_date_newarrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 31, 13, 37, 56, 37388)),
        ),
    ]
