# Generated by Django 5.0.6 on 2024-07-31 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_product_sale_price_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 1, 1, 17, 38, 151725)),
        ),
    ]
