# Generated by Django 5.0.6 on 2024-08-06 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_rename_address_line_1_order_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='address_line_1',
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(default='default_first_name', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(default='default_last_name', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='address_line_2',
            field=models.CharField(blank=True, default='default_address', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 6, 13, 18, 24, 717214)),
        ),
    ]
