# Generated by Django 5.0.6 on 2024-08-06 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_rename_address_order_address_line_1_address_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='company_name',
            field=models.CharField(default='default_company_name', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(default='default_company_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 6, 13, 41, 23, 323165)),
        ),
    ]
