# Generated by Django 5.0.6 on 2024-08-07 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_color_size_alter_order_date_product_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 7, 15, 43, 52, 62378)),
        ),
    ]
