# Generated by Django 5.0.6 on 2024-08-07 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_alter_order_date_productattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 7, 19, 38, 22, 889149)),
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
