# Generated by Django 5.0.6 on 2024-08-07 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_alter_order_date_delete_productattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 7, 21, 11, 21, 22899)),
        ),
    ]
