# Generated by Django 5.0.6 on 2024-08-07 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_alter_order_date_productattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='var_image',
            field=models.ImageField(default='images/default.jpg', upload_to='var_images/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 7, 22, 26, 36, 335093)),
        ),
    ]
