# Generated by Django 5.0.6 on 2024-08-08 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_productattribute_var_image_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 8, 9, 38, 10, 11948)),
        ),
    ]
