# Generated by Django 5.0.6 on 2024-08-09 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_alter_order_date_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 9, 12, 50, 18, 880074)),
        ),
    ]
